Vagrant.configure('2') do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true

  vm_name = 'static-instance-vagrant'
  config.vm.define vm_name do |c|
    c.vm.host_name = vm_name
    c.vm.box = 'debian/jessie64'
  end
end
