# spell-checker:ignore packit specfile copr epel
specfile_path: dist/molecule.spec
srpm_build_deps:
  - bash
  - git
  - python3-build
  - python3-pip
  - python3-setuptools
  - python3-setuptools_scm+toml
  - python3-wheel
actions:
  create-archive:
    # packit.dev service does have these module pre-installed:
    - python3 -m pip install --user build setuptools-scm
    - python3 -m build --sdist --outdir dist
    - sh -c "ls dist/molecule-*.tar.gz"
  get-current-version:
    - ./tools/get-version.sh
  post-upstream-clone:
    - ./tools/update-version.sh
jobs:
  - job: copr_build
    metadata:
      targets:
        # Unable to build `centos-stream` due to missing python3-setuptools_scm_git_archive
        # which is part of EPEL.
        # - centos-stream-x86_64
        # - epel-8-x86_64
        # Unable to build fedora-stable as it includes both 34 and 35 and on first one we do not have python3-setuptools_scm
        # - fedora-stable
        - fedora-rawhide-x86_64
    trigger: pull_request
  # - job: tests
  #   trigger: pull_request
  #   metadata:
  #     targets:
  #     - fedora-all
  # - job: propose_downstream
  #   trigger: release
  #   metadata:
  #     dist-git-branch: master
