---
version: 2
formats: []

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    # One https://readthedocs.org/dashboard/molecule/environmentvariables/ we
    # do have PIP_CONSTRAINTS=requirements.txt which ensures we install only
    # pinned requirements that that we know to be working.
    - method: pip
      path: .
      extra_requirements:
        - docs
