version: 2

mkdocs:
  fail_on_warning: true

build:
  apt_packages:
    - libkrb5-dev # <- krb5-config <- pyspnego[kerberos]
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
