---
version: 2

mkdocs:
  fail_on_warning: true
  configuration: mkdocs.yml

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - pip install --user tox
    - python3 -m tox -e docs
python:
  install:
    - method: pip
      path: tox
    - method: pip
      path: .
      extra_requirements:
        - docs
submodules:
  include: all
  recursive: true
