version: 2

mkdocs:
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
