version: "3.7"
services:
  dev:
    build:
      context: .
    volumes:
      - "./:/etc/molecule"
      - "./tools/entrypoint.sh:/usr/local/bin/entrypoint.sh"
    privileged: true
    entrypoint: entrypoint.sh
