# This file is only used for testing purposes as it helps ansible-lint to
# install dependencies when these are missing.
collections:
  - name: community.crypto
  - name: community.docker
    version: ">=3.10.2"
  - name: containers.podman
  - name: kubernetes.core
