---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install some basic packages because LXC containers are bare
      raw: |
        if [ -x "$(command -v apt-get)" ]
        then
          apt-get update && apt-get install -y ca-certificates curl python sudo
        elif [ -x "$(command -v yum)" ]
        then
          yum install -y ca-certificates curl python sudo
        elif [ -x "$(command -v zypper)" ]
        then
          zypper -n --gpg-auto-import-keys refresh && zypper -n install -y ca-certificates ca-certificates-cacert ca-certificates-mozilla curl python python-xml sudo
        elif [ -x "$(command -v apk)" ]
        then
          apk update && apk add ca-certificates curl python sudo
        elif [ -x "$(command -v pacman)" ]
        then
          pacman -Syu --noconfirm ca-certificates curl python2 sudo
        elif [ -x "$(command -v dnf)" ]
        then
          dnf --assumeyes install ca-certificates curl python python-devel python2-dnf sudo
        elif [ -x "$(command -v emerge)" ]
        then
          emerge --ask n ca-certificates curl dev-lang/python-2 gentoolkit sudo
        fi
