# Manually perform the following:
#
# newgrp lxd
# sudo lxd init
# sudo pip install -U pip
# cd /vagrant
# sudo pip install -r requirements.txt -r test-requirements.txt -r doc-requirements.txt
# sudo pip install -e .
# py.test test/functional/lxd/ -sv

Vagrant.configure('2') do |config|
  config.vm.synced_folder '../../../', '/vagrant'

  config.vm.define 'molecule-lxd-xenial' do |c|
    c.vm.box = 'ubuntu/xenial64'
    c.vm.provision 'shell', inline: <<-SCRIPT
      sudo apt-get update
      sudo apt-get install -y python-pip libssl-dev libffi-dev lxd
    SCRIPT

    c.vm.host_name = 'molecule-lxd-xenial'
  end
end
