---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
  {%- if cookiecutter.driver_name == 'delegated' %}
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
  {%- endif %}
platforms:
{%- if cookiecutter.driver_name == 'docker' %}
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
{%- elif cookiecutter.driver_name == 'podman' %}
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
{%- else %}
  - name: instance
{%- endif %}
provisioner:
  name: {{ cookiecutter.provisioner_name }}
verifier:
  name: {{ cookiecutter.verifier_name }}
