---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
{%- if cookiecutter.driver_name == 'vagrant' %}
  provider:
    name: virtualbox
{%- endif %}
lint:
  name: {{ cookiecutter.lint_name }}
platforms:
{%- if cookiecutter.driver_name == 'docker' %}
  - name: instance
    image: docker.io/centos:7
{%- elif cookiecutter.driver_name == 'openstack' %}
  - name: instance
    image: Ubuntu-16.04
    flavor: NO-Nano
{%- elif cookiecutter.driver_name == 'podman' %}
  - name: instance
    image: docker.io/centos:7
{%- elif cookiecutter.driver_name == 'vagrant' %}
  - name: instance
    box: ubuntu/xenial64
{%- else %}
  - name: instance
{%- endif %}
provisioner:
  name: {{ cookiecutter.provisioner_name }}
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
verifier:
  name: {{ cookiecutter.verifier_name }}
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
