---
{% raw %}
- name: Teardown
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Destroy molecule instance(s)
      lxd_container:
        name: "{{ molecule_file | molecule_instance_with_scenario_name(item.name) }}"
        state: absent
        force_stop: "{{ item.force | default(True) }}"
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw %}
