{% raw -%}
FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash && apt-get clean; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash; \
    elif [ $(command -v pacman) ]; then pacman --sync --noconfirm --refresh python2 bash && yes | pacman --sync --clean --clean; \
    elif [ $(command -v dnf) ]; then dnf makecache fast && dnf --assumeyes install python python-devel python2-dnf bash && dnf clean all; \
    elif [ $(command -v emerge) ]; then emerge --ask n =dev-lang/python-2\* gentoolkit; fi
{%- endraw %}
