---
{% raw -%}
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Create molecule instance(s)
      lxc_container:
        name: "{{ item.name | instance_with_scenario_name(molecule_yml.scenario.name) }}"
        container_log: yes
        template: ubuntu
        state: started
        template_options: --release xenial
        container_command: |
          until ping -c1 google.com &>/dev/null; do :; done
          apt-get update
          apt-get install -y python-minimal
      with_items: "{{ molecule_yml.platforms }}"
{% endraw -%}
