---
{% raw -%}
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:
    - name: Create molecule instance(s)
      lxc_container:
        name: "{{ item.name }}"
        container_log: true
        template: ubuntu
        state: started
        template_options: --release xenial
        container_command: |
          until ping -c1 google.com &>/dev/null; do :; done
          apt-get update
          apt-get install -y python-minimal
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw %}
