---
{% raw %}
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  tasks:
    - name: Destroy molecule instance(s)
      lxc_container:
        name: "{{ item.name }}"
        state: absent
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw %}
