---
{% raw -%}
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env','MOLECULE_DEBUG') | bool }}"
  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | molecule_from_yml }}"

  tasks:

    - name: Create molecule instance(s)
      vmware_guest:
        name: "{{ item.name }}"
        datacenter: "{{ item.datacenter }}"
        cluster: "{{ item.cluster }}"
        folder: "{{ item.folder }}"
        state: absent
        force: yes
        hostname: "{{ molecule_vmware_creds.hostname }}"
        username: "{{ molecule_vmware_creds.username }}"
        password: "{{ molecule_vmware_creds.password }}"
        validate_certs: "{{ item.validate_certs }}"
        wait_for_ip_address: true
      register: server
      with_items: "{{ molecule_yml.platforms }}"

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config
      set_fact:
        instance_conf: {}
    - name: Dump instance config
      copy:
        # NOTE(retr0h): Workaround for Ansible 2.2.
        #               https://github.com/ansible/ansible/issues/20885
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
{%- endraw %}