---
- name: Converge
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  tasks:
    - name: Deploy Ansible Role 
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"