---
- name: Converge
  hosts: all
  gather_facts: true
  become: yes
  become_method: ansible.builtin.sudo
  tasks:
    - name: Deploy Ansible Role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
