#  Copyright (c) 2015-2018 Cisco Systems, Inc.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to
#  deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#  sell copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.
"""Schema v3 Validation Module."""

from __future__ import annotations

import json
import logging

from pathlib import Path
from typing import TYPE_CHECKING

from jsonschema import validate as jsonschema_validate
from jsonschema.exceptions import ValidationError

from molecule import api
from molecule.data import __file__ as data_module


if TYPE_CHECKING:
    from molecule.types import ConfigData


LOG = logging.getLogger(__name__)


def validate(c: ConfigData) -> list[str]:
    """Perform schema validation.

    Args:
        c: Dictionary of configuration data.

    Returns:
        Any errors generated by the schema validation.
    """
    schema_files = _collect_schema_files(c)
    schemas = []
    for schema_file in schema_files:
        with Path(schema_file).open(encoding="utf-8") as f:
            schemas.append(json.load(f))

    try:
        for schema in schemas:
            jsonschema_validate(c, schema)
    except ValidationError as exc:
        return [_format_validation_error(exc)]

    return []


def _collect_schema_files(c: ConfigData) -> list[str]:
    """Collect schema files for validation including driver schema.

    Args:
        c: Dictionary of configuration data.

    Returns:
        List of schema file paths.
    """
    schema_files = [str(Path(data_module).parent / "molecule.json")]

    if "driver" not in c or "name" not in c["driver"]:
        return schema_files

    driver_name = c["driver"]["name"]
    driver_schema_file = None
    if driver_name in api.drivers():
        driver_schema_file = api.drivers()[driver_name].schema_file()

    if driver_schema_file is None:
        LOG.warning("Driver %s does not provide a schema.", driver_name)
    elif not Path(driver_schema_file).exists():
        LOG.warning("Schema %s for driver %s not found.", driver_schema_file, driver_name)
    else:
        schema_files.append(driver_schema_file)

    return schema_files


def _format_validation_error(exc: ValidationError) -> str:
    """Format a validation error into a user-friendly message.

    Args:
        exc: The validation error to format.

    Returns:
        Formatted error message string.
    """
    is_driver_name_error = exc.json_path == "$.driver.name" and exc.message.endswith(
        (
            "is not of type 'string'",
            "is not valid under any of the given schemas",
        ),
    )
    if not is_driver_name_error:
        return exc.message

    wrong_driver_name = str(exc.message.split()[0])
    if isinstance(exc.schema, dict):
        driver_name_err_msg = exc.schema["messages"]["anyOf"]
    else:
        driver_name_err_msg = "is not a valid driver name"
    return f"{wrong_driver_name} {driver_name_err_msg}"
