"""Generate C4 diagram Python files from crawled dependency data.

Usage:
    python3 generate_diagram.py [--input dependencies.json] \
        [--output-dir .architecture-diagrams] [--level context|container|component]

Reads the crawler's dependencies.json and produces executable Python files
that use the c4-diagrams DSL. Each file can be rendered to PNG via `c4 export`.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    from arch_models import (  # pylint: disable=import-error
        CrawlResult,
        RepoTier,
    )
except ImportError:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from arch_models import (
        CrawlResult,
        RepoTier,
    )

PROVENANCE = (
    "Generated by architecture-diagram skill — "
    "https://github.com/ansible/team-devtools/tree/main/.agents/skills/architecture-diagram"
)


def _safe_var(name: str) -> str:
    """Turn a repo slug or component name into a valid Python variable.

    Args:
        name: Repo slug or component name.

    Returns:
        Valid Python identifier.

    """
    result = name.replace("/", "_").replace("-", "_").replace(".", "_").replace("@", "").replace(" ", "_").lower()
    result = re.sub(r"[^a-z0-9_]", "", result)
    result = re.sub(r"_+", "_", result).strip("_")
    if result and result[0].isdigit():
        result = "n" + result
    return result or "unnamed"


# ---------------------------------------------------------------------------
# L1 -- System Context Diagram
# ---------------------------------------------------------------------------


def generate_system_context(result: CrawlResult, output_dir: Path) -> Path:
    """Generate the L1 System Context diagram.

    Args:
        result: Crawl result data.
        output_dir: Directory to write the diagram file.

    Returns:
        Path to the generated diagram file.

    """
    out = output_dir / "l1_system_context.py"

    # Group repos into logical systems
    adt_repos = [
        s for s, e in result.repos.items() if e.tier in (RepoTier.PRIMARY, RepoTier.EXPERIMENTAL, RepoTier.COMMUNITY)
    ]
    container_repos = [s for s, e in result.repos.items() if e.tier == RepoTier.CONTAINER]
    ai_platform_repos = [s for s, e in result.repos.items() if e.tier == RepoTier.AI_PLATFORM]
    adjacent_repos = [s for s, e in result.repos.items() if e.tier == RepoTier.ADJACENT]

    lines = [
        '"""L1 System Context — Ansible Dev Tools Ecosystem."""',
        "from c4 import *",
        "",
        "",
        f'with SystemContextDiagram("{PROVENANCE}") as diagram:',
        "",
        "    # --- Personas ---",
        "    content_author = Person(",
        '        "Ansible Content Author",',
        '        "Writes playbooks, roles, and collections using Ansible.",',
        "    )",
        "",
        "    # --- ADT System ---",
        '    with EnterpriseBoundary("Ansible DevTools"):',
        "        adt = System(",
        '            "Ansible Dev Tools",',
        '            "Suite of CLI tools, libraries, and extensions for Ansible content development. '
        f'Includes {len(adt_repos)} projects.",',
        "        )",
        "",
        "        vscode_ext = System(",
        '            "VS Code Ansible Extension",',
        '            "IDE extension with language server, MCP server, and Python tool integrations.",',
        "        )",
        "",
    ]

    if container_repos:
        lines += [
            "    # --- Downstream Containers ---",
            '    with SystemBoundary("AAP Downstream Containers"):',
        ]
        for slug in container_repos:
            entry = result.repos[slug]
            var = _safe_var(slug)
            short = slug.split("/")[-1]
            desc = entry.description.replace('"', '\\"')
            lines.append(f'        {var} = System("{short}", "{desc}", alias="{var}")')
        lines.append("")

    if ai_platform_repos:
        lines += [
            "    # --- AI Platform ---",
        ]
        for slug in ai_platform_repos:
            entry = result.repos[slug]
            var = _safe_var(slug)
            short = slug.split("/")[-1].title()
            desc = entry.description.replace('"', '\\"')
            lines.append(f'    {var} = System("{short}", "{desc}", alias="{var}")')
        lines.append("")

    if adjacent_repos:
        lines += [
            "    # --- Adjacent Systems ---",
        ]
        for slug in adjacent_repos:
            entry = result.repos[slug]
            var = _safe_var(slug)
            short = slug.split("/")[-1].upper()
            desc = entry.description.replace('"', '\\"')
            lines.append(f'    {var} = SystemExt("{short}", "{desc}", alias="{var}")')
        lines.append("")

    lines += [
        "    # --- External Systems ---",
        "    aap_portal = SystemExt("
        '"AAP Portal", "Custom Backstage instance for AAP self-service", alias="aap_portal"'
        ")",
        '    pypi = SystemExt("PyPI", "Python package index", alias="pypi")',
        '    github = SystemExt("GitHub", "Source code hosting and CI/CD", alias="github")',
        '    galaxy = SystemExt("Ansible Galaxy", "Collection distribution", alias="galaxy")',
        '    llm_apis = SystemExt("LLM Provider APIs", "OpenAI, Anthropic, Gemini, Ollama", alias="llm_apis")',
        "",
        "    # --- Relationships ---",
        '    content_author >> Rel("Develops content with") >> adt',
        '    content_author >> Rel("Edits in IDE") >> vscode_ext',
        '    vscode_ext >> Rel("Spawns CLI tools") >> adt',
        '    adt >> Rel("Publishes packages") >> pypi',
        '    adt >> Rel("Hosts code") >> github',
        '    adt >> Rel("Publishes collections") >> galaxy',
    ]

    if container_repos:
        lines.append(
            f'    adt >> Rel("Packaged into") >> {_safe_var(container_repos[0])}',
        )
        lines.append(
            f'    aap_portal >> Rel("Consumes ADT web server") >> {_safe_var(container_repos[0])}',
        )

    lines.append('    aap_portal >> Rel("Consumes REST API") >> adt')

    if ai_platform_repos:
        ai_var = _safe_var(ai_platform_repos[0])
        lines.append(f'    {ai_var} >> Rel("Provides LLM access") >> llm_apis')

    if adjacent_repos:
        apme_var = _safe_var(adjacent_repos[0])
        if ai_platform_repos:
            lines.append(
                f'    {apme_var} >> Rel("AI remediation via") >> {_safe_var(ai_platform_repos[0])}',
            )

    code = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(code)
    return out


# ---------------------------------------------------------------------------
# L2 -- Container Diagram
# ---------------------------------------------------------------------------


def generate_container_diagram(result: CrawlResult, output_dir: Path) -> Path:  # noqa: PLR0912
    """Generate the L2 Container diagram showing individual projects.

    Args:
        result: Crawl result data.
        output_dir: Directory to write the diagram file.

    Returns:
        Path to the generated diagram file.

    """
    out = output_dir / "l2_container.py"

    lines = [
        '"""L2 Container — Ansible Dev Tools Ecosystem."""',
        "from c4 import *",
        "",
        "",
        f'with ContainerDiagram("{PROVENANCE}") as diagram:',
        "",
        "    # --- Personas ---",
        "    content_author = Person(",
        '        "Ansible Content Author",',
        '        "Writes playbooks, roles, and collections.",',
        "    )",
        "",
    ]

    # Group by tier into boundaries
    tier_groups = {
        RepoTier.PRIMARY: ("ADT Core Tools", "adt_core", []),
        RepoTier.EXPERIMENTAL: ("ADT Testing and Automation", "adt_testing", []),
        RepoTier.COMMUNITY: ("Community", "community", []),
        RepoTier.CONTAINER: ("Downstream Containers", "downstream", []),
        RepoTier.AI_PLATFORM: ("Abbenay - AI Daemon", "abbenay_ai", []),
        RepoTier.ADJACENT: ("APME - Adjacent", "apme_adjacent", []),
    }
    for slug, entry in result.repos.items():
        if entry.tier in tier_groups:
            tier_groups[entry.tier][2].append((slug, entry))

    var_map: dict[str, str] = {}

    for tier, (boundary_label, boundary_alias, entries) in tier_groups.items():
        if not entries:
            continue

        lines.append(f"    # --- {boundary_label} ---")
        lines.append(
            f'    with ContainerBoundary("{boundary_label}", alias="{boundary_alias}"):',
        )

        for slug, entry in entries:
            var = _safe_var(slug)
            var_map[slug] = var
            tech = entry.language.value
            short_name = slug.rsplit("/", maxsplit=1)[-1]
            desc = entry.description.replace('"', '\\"')

            if tier == RepoTier.CONTAINER:
                lines.append(
                    f'        {var} = Container("{short_name}", "{desc}", technology="Container Image", alias="{var}")',
                )
            else:
                lines.append(
                    f'        {var} = Container("{short_name}", "{desc}", technology="{tech}", alias="{var}")',
                )
        lines.append("")

    # Add components discovered inside repos (vscode lang server, MCP, abbenay sub-packages)
    for comp in result.components:
        var = _safe_var(comp.name)
        if var in var_map.values():
            var = var + "_comp"
        var_map[comp.name] = var
        desc = comp.description.replace('"', '\\"')
        tech = comp.technology.replace('"', '\\"')
        lines.append(
            f'    {var} = Container("{comp.name}", "{desc}", technology="{tech}", alias="{var}")',
        )

    lines.append("")

    # Container images built by repos (only show images with registry names)
    image_rels: list[str] = []
    seen_image_vars: set[str] = set()
    for container in result.containers:
        if "/" not in container.image_name:
            continue
        var = _safe_var(container.image_name)
        if var in seen_image_vars:
            continue
        seen_image_vars.add(var)
        short = container.image_name.split("/")[-1]
        var_map[container.image_name] = var
        lines.append(
            f'    {var} = Container("{short}", '
            f'"Published container image", technology="Container Image", alias="{var}")',
        )
        repo_var = var_map.get(container.repo_slug)
        if repo_var:
            image_rels.append(f'    {repo_var} >> Rel("builds") >> {var}')

    if seen_image_vars:
        lines.append("")

    # External systems
    lines += [
        "    # --- External Dependencies ---",
        "    aap_portal = ContainerExt("
        '"AAP Portal", "Custom Backstage instance for AAP self-service", '
        'technology="Backstage", alias="aap_portal"'
        ")",
        "    ansible_builder = ContainerExt("
        '"ansible-builder", "Execution environment builder", '
        'technology="Python", alias="ansible_builder"'
        ")",
        "    ansible_runner = ContainerExt("
        '"ansible-runner", "Playbook execution engine", '
        'technology="Python", alias="ansible_runner"'
        ")",
        "    ansible_core = ContainerExt("
        '"ansible-core", "Core Ansible engine", '
        'technology="Python", alias="ansible_core"'
        ")",
        "    community_molecule = ContainerExt("
        '"community.molecule", "Molecule collection", '
        'technology="Ansible Collection", alias="community_molecule"'
        ")",
        "    vscode_yaml = ContainerExt("
        '"vscode-yaml", "YAML language support", '
        'technology="TypeScript", alias="vscode_yaml"'
        ")",
        "    llm_apis = ContainerExt("
        '"LLM Provider APIs", "OpenAI, Anthropic, Gemini, Ollama", '
        'technology="HTTP APIs", alias="llm_apis"'
        ")",
        "",
    ]

    ext_vars = {
        "ansible/ansible-builder": "ansible_builder",
        "ansible/ansible-runner": "ansible_runner",
        "ansible/ansible-core": "ansible_core",
        "ansible-collections/community.molecule": "community_molecule",
        "redhat-developer/vscode-yaml": "vscode_yaml",
    }

    # Relationships from crawl data
    lines.append("    # --- Relationships (discovered from actual repos) ---")
    lines.append(
        '    content_author >> Rel("Develops with") >> ' + var_map.get("ansible/ansible-dev-tools", "adt"),
    )
    lines.append("")

    for rel in result.relationships:
        src_var = var_map.get(rel.source) or ext_vars.get(rel.source)
        tgt_var = var_map.get(rel.target) or ext_vars.get(rel.target)
        if not src_var or not tgt_var:
            continue
        if src_var == tgt_var:
            continue
        lines.append(f'    {src_var} >> Rel("{rel.label}") >> {tgt_var}')

    # Container image build relationships
    for img_rel in image_rels:
        lines.append(img_rel)

    # AAP Portal consumes the downstream container and ADT REST API
    lines.append("")
    lines.append("    # --- AAP Portal (external consumer) ---")
    devtools_container_var = var_map.get(
        "ansible-automation-platform/ansible-devtools-container",
    )
    adt_var = var_map.get("ansible/ansible-dev-tools")
    if devtools_container_var:
        lines.append(
            f'    aap_portal >> Rel("Consumes ADT web server") >> {devtools_container_var}',
        )
    if adt_var:
        lines.append(f'    aap_portal >> Rel("Consumes REST API") >> {adt_var}')

    code = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(code)
    return out


# ---------------------------------------------------------------------------
# L3 -- Component Diagram (per-repo, on request)
# ---------------------------------------------------------------------------


def generate_component_diagram(
    result: CrawlResult,
    repo_slug: str,
    output_dir: Path,
) -> Path | None:
    """Generate an L3 Component diagram for a single repo.

    Args:
        result: Crawl result data.
        repo_slug: Repository slug to generate diagram for.
        output_dir: Directory to write the diagram file.

    Returns:
        Path to the generated diagram file, or ``None`` on failure.

    """
    entry = result.repos.get(repo_slug)
    if not entry:
        print(f"  Unknown repo: {repo_slug}", file=sys.stderr)
        return None

    components = [c for c in result.components if c.repo_slug == repo_slug]
    if not components:
        print(f"  No components discovered for {repo_slug}", file=sys.stderr)
        return None

    safe_slug = _safe_var(repo_slug)
    out = output_dir / f"l3_component_{safe_slug}.py"

    lines = [
        f'"""L3 Component — {repo_slug}."""',
        "from c4 import *",
        "",
        "",
        f'with ComponentDiagram("{repo_slug} Components") as diagram:',
        "",
        f'    with ContainerBoundary("{repo_slug}", alias="{safe_slug}"):',
    ]

    var_map: dict[str, str] = {}
    for comp in components:
        var = _safe_var(comp.name)
        var_map[comp.name] = var
        desc = comp.description.replace('"', '\\"')
        tech = comp.technology.replace('"', '\\"')
        lines.append(
            f'        {var} = Component("{comp.name}", "{desc}", technology="{tech}", alias="{var}")',
        )

    lines.append("")

    # Collect relationships involving this repo's components
    repo_rels = [r for r in result.relationships if r.source in var_map or r.target in var_map]

    # Identify external targets/sources that need ComponentExt definitions
    ext_vars: dict[str, str] = {}
    for rel in repo_rels:
        for endpoint in (rel.source, rel.target):
            if endpoint not in var_map and endpoint not in ext_vars:
                var = _safe_var(endpoint) + "_ext"
                ext_vars[endpoint] = var
                short_name = endpoint.split("/")[-1] if "/" in endpoint else endpoint
                ext_desc = result.repos[endpoint].description.replace('"', '\\"') if endpoint in result.repos else ""
                lines.append(
                    f'    {var} = ComponentExt("{short_name}", "{ext_desc}", alias="{var}")',
                )

    if ext_vars:
        lines.append("")

    for rel in repo_rels:
        src_var = var_map.get(rel.source) or ext_vars.get(rel.source)
        tgt_var = var_map.get(rel.target) or ext_vars.get(rel.target)
        if src_var and tgt_var and src_var != tgt_var:
            lines.append(f'    {src_var} >> Rel("{rel.label}") >> {tgt_var}')

    code = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(code)
    return out


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Generate C4 diagram files from crawled dependency data."""
    parser = argparse.ArgumentParser(
        description="Generate C4 diagram files from crawl data",
    )
    parser.add_argument(
        "--input",
        default=".architecture-diagrams/dependencies.json",
        help="Crawl result JSON",
    )
    parser.add_argument(
        "--output-dir",
        default=".architecture-diagrams",
        help="Output directory for diagram .py files",
    )
    parser.add_argument(
        "--level",
        choices=["context", "container", "component", "all"],
        default="all",
        help="Which C4 level(s) to generate",
    )
    parser.add_argument(
        "--component-repo",
        default="",
        help="Repo slug for L3 component diagram (requires --level component)",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading crawl data from {input_path} ...")
    result = CrawlResult.from_json(input_path)
    print(
        f"  {len(result.repos)} repos, {len(result.relationships)} relationships, {len(result.components)} components",
    )

    generated: list[Path] = []

    if args.level in ("context", "all"):
        p = generate_system_context(result, output_dir)
        generated.append(p)
        print(f"  Generated L1 System Context: {p}")

    if args.level in ("container", "all"):
        p = generate_container_diagram(result, output_dir)
        generated.append(p)
        print(f"  Generated L2 Container: {p}")

    if args.level == "component":
        if not args.component_repo:
            # Generate for all repos that have components
            repos_with_components = {c.repo_slug for c in result.components}
            for slug in sorted(repos_with_components):
                p = generate_component_diagram(result, slug, output_dir)
                if p:
                    generated.append(p)
                    print(f"  Generated L3 Component ({slug}): {p}")
        else:
            p = generate_component_diagram(result, args.component_repo, output_dir)
            if p:
                generated.append(p)
                print(f"  Generated L3 Component ({args.component_repo}): {p}")

    if args.level == "all":
        repos_with_components = {c.repo_slug for c in result.components}
        for slug in sorted(repos_with_components):
            p = generate_component_diagram(result, slug, output_dir)
            if p:
                generated.append(p)
                print(f"  Generated L3 Component ({slug}): {p}")

    print(f"\n{len(generated)} diagram file(s) generated in {output_dir}/")


if __name__ == "__main__":
    main()
