---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
platforms:
  - name: instance
{%- if cookiecutter.driver_name in ['containers', 'docker', 'podman'] %}
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
{%- endif %}
provisioner:
  name: {{ cookiecutter.provisioner_name }}
verifier:
  name: {{ cookiecutter.verifier_name }}
