---
# This is an example playbook to execute Ansible tests.

{% raw -%}
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
{% endraw -%}
