---
{% raw -%}
- name: Test for presence of local keypair
  stat:
    path: "{{ keypair_path }}"
  register: keypair_local

- name: Delete remote keypair
  os_keypair:
    name: "{{ keypair_name }}"
    state: absent
  when: not keypair_local.stat.exists

- name: Create keypair
  os_keypair:
    name: "{{ keypair_name }}"
  register: keypair

- name: Persist the keypair
  copy:
    dest: "{{ keypair_path }}"
    content: "{{ keypair.key.private_key }}"
    mode: 0600
  when: keypair.changed
{%- endraw -%}
