# Manually perform the following:
#
# cd /vagrant
# sudo pip install -r requirements.txt -r test-requirements.txt -r doc-requirements.txt
# sudo pip install -e .
# py.test test/functional/lxc/ -sv

Vagrant.configure('2') do |config|
  config.vm.synced_folder '../../../', '/vagrant'

  config.vm.define 'molecule-lxc-xenial' do |c|
    c.vm.box = 'ubuntu/xenial64'
    c.vm.provision 'shell', inline: <<-SCRIPT
      sudo apt-get update
      sudo apt-get install -y python-pip libssl-dev libffi-dev lxc lxc-dev
    SCRIPT

    c.vm.host_name = 'molecule-lxc-xenial'
  end

  config.vm.define 'molecule-lxc-centos' do |c|
    c.vm.box = 'centos/7'
    c.vm.provision 'shell', inline: <<-SCRIPT
      sudo yum install -y epel-release
      sudo yum install -y gcc python-pip openssl-devel libffi-devel lxc lxc-devel
    SCRIPT

    c.vm.host_name = 'molecule-lxc-centos'
  end
end
