name: readiness
# see https://github.com/jesusvasquez333/verify-pr-label-action/issues/9#issuecomment-706639627
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  labels:
    name: labels
    runs-on: ubuntu-latest
    steps:
      - name: Verify presence of required labels
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, feature, skip-changelog, deprecated, major'
